### PR TITLE
Cross-compile for SBT 1.0

### PR DESCRIPTION
**Pull request by nigredo-tori**
This is the first step towards xsbt-webstart for SBT 1.0.

### CODE REVIEW

**Comment by ritschwumm** [comment]
thanks for the contribution - i haven't published their sources yet, but i simply ditched support for sbt 0.13 in all my plugins. would that be a problem for you?

**Comment by nigredo-tori** [comment]
No, not at all.

**Comment by ritschwumm** [comment]
ok, published the sbt 1.x sources for everything.

**Comment by nigredo-tori** [comment]
Thank you!

**Pull request closed without merging**
